src/Entity/TimeTable.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TimeTableRepository")
 */
class TimeTable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Employee", inversedBy="timeTables")
     * @ORM\JoinColumn(nullable=false)
     */
    private $employee;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Absence", inversedBy="timeTables")
     */
    private $absence;


    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $am_start_at;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $am_end_at;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $pm_start_at;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $pm_end_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Day", inversedBy="timeTables")
     * @ORM\JoinColumn(nullable=false)
     */
    private $day;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): self
    {
        $this->employee = $employee;

        return $this;
    }

    public function getAbsence(): ?Absence
    {
        return $this->absence;
    }

    public function setAbsence(?Absence $absence): self
    {
        $this->absence = $absence;

        return $this;
    }
    

    public function getAmStartAt(): ?\DateTimeInterface
    {
        return $this->am_start_at;
    }

    public function setAmStartAt(?\DateTimeInterface $am_start_at): self
    {
        $this->am_start_at = $am_start_at;

        return $this;
    }

    public function getAmEndAt(): ?\DateTimeInterface
    {
        return $this->am_end_at;
    }

    public function setAmEndAt(?\DateTimeInterface $am_end_at): self
    {
        $this->am_end_at = $am_end_at;

        return $this;
    }

    public function getPmStartAt(): ?\DateTimeInterface
    {
        return $this->pm_start_at;
    }

    public function setPmStartAt(?\DateTimeInterface $pm_start_at): self
    {
        $this->pm_start_at = $pm_start_at;

        return $this;
    }

    public function getPmEndAt(): ?\DateTimeInterface
    {
        return $this->pm_end_at;
    }

    public function setPmEndAt(?\DateTimeInterface $pm_end_at): self
    {
        $this->pm_end_at = $pm_end_at;

        return $this;
    }

    public function getDay(): ?Day
    {
        return $this->day;
    }

    public function setDay(?Day $day): self
    {
        $this->day = $day;

        return $this;
    }
}

src/Form/TimeTableType.php
<?php

namespace App\Form;

use App\Entity\Employee;
use App\Entity\TimeTable;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use function Sodium\add;

class TimeTableType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

        ->add('employee', EntityType::class, [
        'class' => Employee::class,
        'choice_label' => 'lastName',
        'label' => 'Nom :'
    ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TimeTable::class,
        ]);
    }
}

src/Controller/TimeTableController.php
<?php

namespace App\Controller;

use App\Entity\Absence;
use App\Entity\Day;
use App\Entity\Employee;
use App\Entity\TimeTable;
use App\Form\AbsenceType;
use App\Form\TimeTableType;
use App\Repository\AbsenceRepository;
use App\Repository\DayRepository;
use App\Repository\MonthRepository;
use App\Repository\TimeTableRepository;
use DateTime;
use Doctrine\ORM\Mapping\Id;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * CRUD absence -> Index(liste), New(Créer), Show(Voir), Edit(Modifier), Delete(Supprimer), Save(Enregistrer)
 * @Route("/time/table")
 */
class TimeTableController extends AbstractController
{
    /**
     * @Route("/", name="time_table_index", methods={"GET"})
     * @param TimeTableRepository $timeTableRepository
     * @return Response
     */
    public function index(TimeTableRepository $timeTableRepository): Response
    {
        return $this->render('time_table/index.html.twig', [
            'time_tables' => $timeTableRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/{id}", name="time_table_new", methods={"GET","POST"})
     * @param Request $request
     * @param Id $id
     * @return Response
     */
    public function new(Request $request, $id): Response
    {
        $time_table = new TimeTable();
        $form = $this->createForm(TimeTableType::class, $time_table);
        $form->handleRequest($request);

        $day = $this->getDoctrine()
            ->getRepository(Day::class)
            ->findAll();

        $absences = $this->getDoctrine()
            ->getRepository(Absence::class)
            ->findAll();

        $absence = new Absence();
        $formAbs = $this->createForm(AbsenceType::class, $absence);
        $formAbs->handleRequest($request);

        if ($formAbs->isSubmitted() && $formAbs->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($absence);
            $entityManager->flush();

            return $this->redirectToRoute('time_table_new');
        }

        return $this->render('time_table/new.html.twig', [
            'form' => $form->createView(),
            'formAbs' => $formAbs->createView(),
            'absence' => $absences,
            'days' => $day,
            'employee' => $employee = $this->getDoctrine()->getRepository(Employee::class)->findOneBy(array('id' => $id))
        ]);
    }

    /**
     * @Route("/delete/{id}", name="time_table_delete", methods={"GET","POST"})
     * @param $id (Id de l'employé selectionné)
     * @return Response
     */
    public function delete($id): Response
    {
        $tables = $this
            ->getDoctrine()
            ->getRepository(TimeTable::class)
            ->findBy(array('employee' => $id));

        if ($tables) {
            foreach ($tables as $table){

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->remove($table);
                $entityManager->flush();
            }
        }

        return $this->redirectToRoute('time_table_new', ['id' => $id] );
    }

    /**
     * @Route("/save", name="time_table_save", methods={"GET", "POST"})
     * @return Response
     * @throws Exception
     */
    public function save(): Response
    {
        $status = "error";
        $message = "";

        if ($_POST) {
            try {
                $status = "success";
                $message = $_POST;
            } catch (Exception $e) {
                $message = $e->getMessage();
            }
        }else{
            $message = $_POST;
        }

        $response = array(
            'status' => $status,
            'message' => $message
        );

        $tables = $_POST['table'];

        $employee = $this
            ->getDoctrine()
            ->getRepository(Employee::class)
            ->findOneBy(array('id' => $_POST['employee']));

        for ($i = 1; $i <= 5; $i ++) {

            $day = $this
                ->getDoctrine()
                ->getRepository(Day::class)
                ->findOneBy(array('id' => $i));

            $timeTable = new TimeTable();

            $entityManager = $this->getDoctrine()->getManager();

                    if (!(empty($tables[$i][0]))) {
                        $absence = $this
                            ->getDoctrine()
                            ->getRepository(Absence::class)
                            ->findOneBy(array('id' => $tables[$i][0]));
                        $timeTable
                            ->setAbsence($absence);
                    }

                    if (!(empty($tables[$i][1]))) {

                        $timeTable
                            ->setAmStartAt(new DateTime($tables[$i][1]));
                    }
                    if (!(empty($tables[$i][2]))) {
                        $timeTable
                            ->setAmEndAt(new DateTime($tables[$i][2]));
                    }
                    if (!(empty($tables[$i][3]))) {
                        $timeTable
                            ->setPmStartAt(new DateTime($tables[$i][3]));
                    }
                    if (!(empty($tables[$i][4]))) {
                        $timeTable
                            ->setPmEndAt(new DateTime($tables[$i][4]));
                    }


                $timeTable
                ->setDay($day)
                ->setEmployee($employee);
            $entityManager->persist($timeTable);
            $entityManager->flush();
        }

        return new JsonResponse($response);

    }


    /**
     * @Route("/{id}", name="time_table_show", methods={"GET"})
     * @param TimeTable $timeTable
     * @return Response
     */
    public function show(TimeTable $timeTable): Response
    {
        return $this->render('time_table/show.html.twig', [
            'time_table' => $timeTable,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="time_table_edit", methods={"GET","POST"})
     * @param Request $request
     * @param TimeTable $timeTable
     * @return Response
     */
    public function edit(Request $request, TimeTable $timeTable): Response
    {
        $form = $this->createForm(TimeTableType::class, $timeTable);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('time_table_index');
        }

        return $this->render('time_table/edit.html.twig', [
            'time_table' => $timeTable,
            'form' => $form->createView(),
        ]);
    }


}

templates/time_table/_delete_form.html.twig
<form method="post" action="{{ path('time_table_delete', {'id': time_table.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ time_table.id) }}">
    <button class="btn">Delete</button>
</form>

templates/time_table/_form.html.twig
{{ form_start(form) }}
<div class="form-group ml-4 mt-3" id="time_table_employee">{{ form_row(form.employee) }}</div>
{{ form_end(form) }}

templates/time_table/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit TimeTable{% endblock %}

{% block body %}
    <h1>Edit TimeTable</h1>

    {{ include('time_table/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('time_table_index') }}">back to list</a>

    {{ include('time_table/_delete_form.html.twig') }}
{% endblock %}

templates/time_table/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TimeTable index{% endblock %}

{% block body %}
    <h1>TimeTable index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Am_start_at</th>
                <th>Am_end_at</th>
                <th>Pm_start_at</th>
                <th>Pm_end_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for time_table in time_tables %}
            <tr>
                <td>{{ time_table.id }}</td>
                <td>{{ time_table.amStartAt ? time_table.amStartAt|date('H:i:s') : '' }}</td>
                <td>{{ time_table.amEndAt ? time_table.amEndAt|date('H:i:s') : '' }}</td>
                <td>{{ time_table.pmStartAt ? time_table.pmStartAt|date('H:i:s') : '' }}</td>
                <td>{{ time_table.pmEndAt ? time_table.pmEndAt|date('H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('time_table_show', {'id': time_table.id}) }}">show</a>
                    <a href="{{ path('time_table_edit', {'id': time_table.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('time_table_new') }}">Create new</a>
{% endblock %}

templates/time_table/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New TimeTable{% endblock %}

{% block body %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" ></script>
    {% include '_menu.html.twig' %}
    <div class="row mt-3">
        <div class="ml-4 mb-3">
            <button type="button" class="btn mt-3 ml-3 mb-3" id="btn-save" onclick="saveTimetable()">Enregistrer</button>
            <a href="{{ path('home') }}"><button class="btn ml-3">Retour</button></a>
            <button type="button" class="btn ml-5" data-toggle="modal" data-target="#exampleModal">Nouveau motif d'absence</button>
        </div>
    </div>


    <h1 class="ml-4">Créer l'emploi du temps type de : {{ employee.firstName }} {{ employee.lastName }} </h1>
    {% for day in days  %}
        {% if ( day.id is same as (6)) or ( day.id is same as (7)) %}
            {#Possibilité d'ajouter des week-ends#}
            {#                <div class="btn-weekend-horaire ml-4" id="btn-weekend-horaire-{{ day.id }}">#}
            {#                <button type="button" class="btn-absence btn-outline-info mt-2" id="btn-weekend-horaire-{{ day.id }}" onclick="horaireWeekEnd()">Ajouter un créneau</button>#}
            {#                </div>#}
            {#            <div class="input-group ml-4 horaires-weekend" id="horaires-weekend-{{ day.id }}">#}
            {#                <input class="form-control col-2 ml-4" id="amStart-{{ day.id }}" type="time" value="09:00">#}
            {#                <input class="form-control col-2 ml-4" id="amEnd-{{ day.id }}" type="time" value="12:00">#}
            {#                <input class="form-control col-2 ml-4" id="pmStart-{{ day.id }}" type="time" value="14:00">#}
            {#                <input class="form-control col-2 ml-4" id="pmEnd-{{ day.id }}" type="time" value="18:00">#}
            {#                <button type="button" class="btn-absence btn-outline-info ml-2" id="btn-absence-{{ day.id }}" onclick="weekendReset()">Annuler Week-end</button>#}
            {#            </div>#}
            {#        </div>#}
        {% else %}
            <div class="ml-4 mr-3 mb-3 mt-5 daily font-weight-bold" id="{{ day.id }}"><div>{{ day.label }} :</div>


                <div class="input-group ml-5 horaires " id="horaires-{{ day.id }}">
                    <input class="form-control col-2 ml-4" id="amStart-{{ day.id }}" type="time" value="09:00" onchange="checkError()">
                    <input class="form-control col-2 ml-4" id="amEnd-{{ day.id }}" type="time" value="12:00" onchange="checkError()">
                    <input class="form-control col-2 ml-4" id="pmStart-{{ day.id }}" type="time" value="14:00" onchange="checkError()">
                    <input class="form-control col-2 ml-4" id="pmEnd-{{ day.id }}" type="time" value="18:00" onchange="checkError()">
                    <button type="button" class="btn btn-absence ml-5" id="btn-absence-{{ day.id }}" onclick="adAbsence()">Absence</button>
                </div>
                <div class='row ml-5'>
                    <div class="select-absence ml-3 col-3" id="absence-{{ day.id }}">
                        <select name="absence" id="absence-select-{{ day.id }}" class="form-control">
                            {% for abs in absence  %}
                                <option value="{{ abs.id }}">{{ abs.label }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="btn-absence-reset ml-4" id="btn-absence-reset-{{ day.id }}">
                        <button type="button" class="btn btn-absence ml-3" onclick="absenceReset()">Annuler l'absence</button>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Enregistrer une nouvelle absence</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ include('timesheet/newAbsence.html.twig') }}
                    <button type="button" class="btn mt-3" data-dismiss="modal">Annuler</button>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        let arr_timetableS = [];

        let getDayId;

        $(".daily").hover(function () {
            currentId = $(this).attr('id')
            getDayId = currentId;
        });

        $('.btn-weekend-reset').hide();
        $('.horaires-weekend').hide();
        $('.select-absence').hide();
        $('.btn-absence-reset').hide();

        // Initialise l'absence ( cache le bouton absence, fait apparaître les cas d'absence et cache les horaires)
        function adAbsence() {
            $('#horaires-' + getDayId).hide();
            $('#absence-' + getDayId).show();
            $('#btn-absence-' + getDayId).hide();
            $('#btn-absence-reset-' + getDayId).show();
        }

        // Annule l'absence (replace les horaires précèdents et le bouton absence)
        function absenceReset() {
            $('#horaires-' + getDayId).show();
            $('#absence-' + getDayId).hide();
            $('#btn-absence-' + getDayId).show();
            $('#btn-absence-reset-' + getDayId).hide();
        }

        // Horaire Week-end
        function horaireWeekEnd() {
            $('#horaires-weekend-' + getDayId).show();
            $('#btn-weekend-horaire-' + getDayId).hide();
            $('#btn-weekend-reset-' + getDayId).show();
            $('#day-horaire-' + getDayId).show();

        }

        // Annule l'horaire du week-end (supprime les horaires et le bouton ajout créneau)
        function weekendReset() {
            $('#horaires-weekend-' + getDayId).hide();
            $('#btn-weekend-horaire-' + getDayId).show();
            $('#btn-weekend-reset-' + getDayId).hide();

        }

        function checkError() {
            for (let dayId = 1; dayId <= 5; dayId++){
                if( parseInt($('#amStart-' + dayId ).val()) > parseInt($('#amEnd-' +  dayId).val())) {
                    $('#amStart-' + dayId).addClass('error');
                }else {
                    $('#amStart-' + dayId).removeClass('error');
                }
                if( parseInt($('#amEnd-' + dayId ).val()) > parseInt($('#pmStart-' +  dayId).val())) {
                    $('#amEnd-' + dayId).addClass('error');
                }else {
                    $('#amEnd-' + dayId).removeClass('error');
                }
                if( parseInt($('#pmStart-' + dayId ).val()) > parseInt($('#pmEnd-' +  dayId).val())) {
                    $('#pmStart-' + dayId).addClass('error');
                }else {
                    $('#pmStart-' + dayId).removeClass('error');
                }
            }
        }


        function saveTimetable() {

            for (let i = 1; i <= 5; i++) {

                let arr_timetable = [];

                if ( $('#amStart-' + i).is(":visible") ){
                    arr_timetable[1] = document.getElementById('amStart-' + i).value;
                } else {
                    arr_timetable[0] = $(":input#absence-select-" + i).val();
                }
                if ( $('#amEnd-' + i).is(":visible") ){
                    arr_timetable[2] = document.getElementById('amEnd-' + i).value;
                }
                if ( $('#pmStart-' + i).is(":visible") ){
                    arr_timetable[3] = document.getElementById('pmStart-' + i).value;
                }
                if ( $('#pmEnd-' + i).is(":visible") ){
                    arr_timetable[4] = document.getElementById('pmEnd-' + i).value;
                }

                arr_timetableS[i] = arr_timetable;

            }
            json = JSON.stringify(arr_timetableS);

            let employee = {{ employee.id }};
            $('#btn-save').hide();
            $.ajax({

                url: '{{ path('time_table_save') }}',
                type: 'POST',
                data:
                    {
                        table : arr_timetableS,
                        employee : employee,
                    },
                dataType: 'data',
                success: alert('La feuille de présence a bien été enregistré !'),
                error: function() {
                    console.log('error');
                }
            });

        }
    </script>
{% endblock %}

templates/time_table/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}TimeTable{% endblock %}

{% block body %}
    <h1>TimeTable</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ time_table.id }}</td>
            </tr>
            <tr>
                <th>Am_start_at</th>
                <td>{{ time_table.amStartAt ? time_table.amStartAt|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Am_end_at</th>
                <td>{{ time_table.amEndAt ? time_table.amEndAt|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Pm_start_at</th>
                <td>{{ time_table.pmStartAt ? time_table.pmStartAt|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Pm_end_at</th>
                <td>{{ time_table.pmEndAt ? time_table.pmEndAt|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('time_table_index') }}">back to list</a>

    <a href="{{ path('time_table_edit', {'id': time_table.id}) }}">edit</a>

    {{ include('time_table/_delete_form.html.twig') }}
{% endblock %}